apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sai-ns
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # or NodePort, LoadBalancer, etc.

  # # kubectl apply -f service.yml
  # # kubectl get services -n sai-ns  
  # # kubectl get svc -n sai-ns
  # # kubectl describe svc nginx-service -n sai-ns
  # # kubectl delete svc nginx-service -n sai-ns
  # # kubectl get pods -n sai-ns
  # # kubectl get pods -n sai-ns -o wide

  # # kubectl get pods -n sai-ns -o wide --show-labels
  # # kubectl get pods -n sai-ns -o wide --show-labels | grep nginx